# Generated by Django 5.2.5 on 2025-08-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('desenvolvedora', models.CharField(blank=True, max_length=20, null=True)),
                ('ano_publicacao', models.IntegerField(blank=True, max_length=255, null=True)),
                ('plataforma', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
